DOCS-10055 Exchange API
mulesoft/docs-exchange pull request #125
Opened 2021-03-03 09:05 UTC by wwarner-salesforce

DOCS-10055 Exchange API

2021-03-09 19:23 UTC, LucasLudueno commented on modules/ROOT/pages/exchange-api.adoc
> +After the API asset includes all the information necessary for consumers to discover, learn, and understand your API, add the server or instance information so consumers can invoke the API. Replace `
```suggestion
After the API asset includes all the information necessary for consumers to discover, learn, and understand your API, add the server or instance information so consumers can invoke the API. Replace `:groupId`, `:assetId`, and `:versionGroup` with the group ID, asset ID, and version ID of the API asset.
```

2021-03-09 19:23 UTC, LucasLudueno commented on modules/ROOT/pages/exchange-api.adoc
> +  -X PATCH \
```suggestion
  -X POST \
```

2021-03-09 19:26 UTC, wwarner-salesforce commented on modules/ROOT/pages/exchange-api.adoc
> +After the API asset includes all the information necessary for consumers to discover, learn, and understand your API, add the server or instance information so consumers can invoke the API. Replace `
Thank you! Fixed.

2021-03-09 19:26 UTC, wwarner-salesforce commented on modules/ROOT/pages/exchange-api.adoc
> +  -X PATCH \
Thank you! Fixed.

2021-03-09 19:27 UTC, LucasLudueno approved these changes, later dismissed

2021-03-09 21:19 UTC, jyotirmi requested changes
Add an overview section before going to describe all the steps in details.

2021-03-09 21:19 UTC, jyotirmi commented on modules/ROOT/pages/exchange-api.adoc
> +
Will, can we add an overview section listing the steps before the detailed sections?

2021-03-09 21:20 UTC, wwarner-salesforce commented on modules/ROOT/pages/exchange-api.adoc
> +
Sure! Adding now.

2021-03-09 21:44 UTC, wwarner-salesforce commented on modules/ROOT/pages/exchange-api.adoc
> +
Added.

2021-03-09 22:00 UTC, jyotirmi requested changes

2021-03-09 22:00 UTC, jyotirmi commented on modules/ROOT/pages/exchange-api.adoc
> +To publish assets to Exchange, this file covers these steps:
Suggested rewording: This topic describes the steps needed to publish an asset to Exchange and add metadata using Exchange APIs. Specifically, it covers the following steps:

2021-03-09 22:52 UTC, wwarner-salesforce commented on modules/ROOT/pages/exchange-api.adoc
> +To publish assets to Exchange, this file covers these steps:
Sounds good! I've added the new text.

2021-03-09 22:55 UTC, jyotirmi approved these changes, later dismissed
Looks good to me.

2021-03-17 15:59 UTC, kbostrom submitted a review, later dismissed
CU, CE

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/about-platform-apis.adoc
>  The Maven facade also lets you publish federated assets.
```suggestion
The Maven facade also enables you to publish federated assets.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +With the Exchange API, you can publish and consume assets, add documentation pages, add or edit categories, and even manage your public portals. For the full API reference, please see the https://any
What do we mean by "the full API reference"? Reference to what kind of info?

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +With the Exchange API, you can publish and consume assets, add documentation pages, add or edit categories, and even manage your public portals. For the full API reference, please see the https://any
Omit "please"; GLOBAL

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +* Connectors
Anypoint Connectors or all kinds of connectors? GLOBAL

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +NOTE: New assets count toward your organization's xref:to-create-an-asset.adoc#asset-limits[asset limit].
ditto edits in #123 re. notice formats. See style ref.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +NOTE: You must have a unique artifact ID and organization ID to publish your asset. The artifact ID consists of the group ID, asset ID, and version.
This is not a note; it is another requirement.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This topic describes the steps needed to publish an asset to Exchange and add metadata using Exchange APIs:
GLOBALLY omit self-reference phrases such as "this topic," "the following section," and so on; see style ref.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +== Overview
Weak heading, esp. since the content is not an overview of the API but rather a list of required tasks.
```suggestion
== Tasks Required to Publish an Asset to Exchange
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This topic describes the steps needed to publish an asset to Exchange and add metadata using Exchange APIs:
```suggestion
Perform the following tasks to publish an asset to Exchange and add metadata using Exchange APIs:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +. Log in to Anypoint Platform and click Access Management.
```suggestion
. Log in to Anypoint Platform and click *Access Management*.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +. Click the organization name for the top level or a business group, and view your organization ID in the organization info screen.
ditto edit question about this same sentence in #123

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +. Copy the organization ID and use it in the following examples.
```suggestion
. Copy the organization ID and use it when you try out examples.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Your organization administrator sets the access token expiration time to a value from 15 to 180 minutes. If you perform a search or other operation that requires more time, you will need a new token.
```suggestion
Invoking any Exchange API requires an access token. Note that the access token provided by your organization administrator expires somewhere between 15 to 180 minutes, so if you perform a search or other operation that requires more time, you must request a subsequent token.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Replace `ANYPOINT_USERNAME` with your Anypoint Platform user account name and replace `ANYPOINT_PASSWORD` with your password.
```suggestion
. Obtain an access token with a cURL command such as the following:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +
Replace `ANYPOINT_USERNAME` with your Anypoint Platform user account name and replace `ANYPOINT_PASSWORD` with your password.

You can also use Postman or another application for sending HTTP commands.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +With Exchange API version 2 you can publish assets to Exchange either by submitting multipart form data or by passing a .pom file that contains the data.
```suggestion
With Exchange API version 2 you can publish assets to Exchange either by submitting multipart form data or by passing a POM file that contains the data.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +The API can upload all supported asset types, including REST APIs, SOAP APIs, HTTP APIs, API fragments, connectors, Mule applications, examples, templates, policies, and custom assets.
GLOBALLY clarify "connectors" in this topic set.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This example shows how to publish a REST API (RAML specification).
ditto prev. edits about self-reference.
We need topics to be independent; this one should not reference the next.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Each API call to create an asset specifies multipart properties.
```suggestion
Each API call to create an asset specifies multipart properties:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +|type |The type of the asset to be created. |Required if the type cannot be inferred from the file extension
```suggestion
|type |The type of asset to be created. |Required if the type cannot be inferred from the file extension
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +|dependencies |A string of comma-separated dependencies, defined as: `dependencies=GROUP_ID:ASSET_ID:VERSION,GROUP_ID:ASSET_ID:VERSION` |Optional
```suggestion
|dependencies |A string of comma-separated dependencies, defined as `dependencies=GROUP_ID:ASSET_ID:VERSION,GROUP_ID:ASSET_ID:VERSION`. |Optional
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +|keywords |A string of comma-separated values to be saved as an asset's attributes. Search queries can find assets by keyword. Example: `keywords=api,raml,auth,jwt,token` |Optional
```suggestion
|keywords |A string of comma-separated values to be saved as an asset's attributes. Search queries can find assets by keyword, for example, `keywords=api,raml,auth,jwt,token`. |Optional
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +|properties |Some asset types require additional properties specified with the properties prefix, such as `apiVersion`, `mainFile`, or `assetLink`. Example: `properties.apiVersion = v1` |May be requi
```suggestion
|properties |Some asset types require additional properties specified with the properties prefix, such as `apiVersion`, `mainFile`, or `assetLink`, for example, `properties.apiVersion = v1`. |Might be required for some properties and some asset types
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This example uses multipart form data to upload a RAML API spec to Exchange.
```suggestion
The following example uses multipart form data to upload a RAML API specification to Exchange.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Replace `/file-path/training-american-flights-api-1.0.0-raml.zip` with your local file path.
```suggestion
Replace `/file-path/training-american-flights-api-1.0.0-raml.zip` with your local file path:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +To specify the asset, replace the identifiers `:groupId`, `:assetId`, and `:version`.
```suggestion
The following example shows how to insert or replace tags on an asset. Each asset is uniquely identified by the combination of its group ID, asset ID, and version. To specify the asset, replace the identifiers `:groupId`, `:assetId`, and `:version`.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +NOTE: This command replaces any existing tags on the asset.
```suggestion
Note that this command replaces any existing tags on the asset.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +To specify the asset, replace the identifiers `:groupId`, `:assetId`, and `:version`.
I would combine all these again.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This example uses a previously created category with the name `apiType` and sets that category value to "System API" on the asset.
```suggestion
This example uses a previously created category with the name `apiType` and sets that category value to `System API` on the asset.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +
GLOBALLY condense these individual sentences into a single intro para; I'll stop marking the rest.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +This example uses a previously created custom field with name `subType` and sets that category value to "OAS" on the asset.
```suggestion
This example uses a previously created custom field with name `subType` and sets that category value to `OAS` on the asset.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Each Exchange asset has associated documentation to provide an overview and other information about the asset. These APIs require the Exchange administrator or Exchange contributor permissions.
Are we equating asset with API? Clarify "These APIs".

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +To add a new documentation page, use this command and replace `:groupId`, `:assetId`, and `:version` with the values for your asset.
```suggestion
To add a new documentation page, use this command and replace `:groupId`, `:assetId`, and `:version` with the values for your asset:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +When the command succeeds it returns the `pageId` of the newly created page.
```suggestion
When the command succeeds, it returns the `pageId` value for the newly created page.
```
OR
```suggestion
When the command succeeds, it returns the page ID of the newly created page.
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +Exchange shows the new draft page on the asset's Exchange portal page under the default Home page. To edit this page and publish the draft, use either the portal user interface or the API steps below
ditto re. "below": topics must be independent for reusability.

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +To add your Markdown content, use this command and replace `:pageId` with the pageId returned by the previous command.
```suggestion
To add your Markdown content, use this command and replace `:pageId` with the page ID you obtained earlier. 
```
ditto re. referring to a separate subtopic

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +When the content is ready, change the page's draft status to published by using this command. Publishing the draft publishes all the pages and content associated with the asset and currently in draft
```suggestion
Publishing the draft publishes all the pages and content associated with the asset and currently in draft status. When the content is ready, change the page's draft status to published by using this command:
```

2021-03-17 15:59 UTC, kbostrom commented on modules/ROOT/pages/exchange-api.adoc
> +After the API asset includes all the information necessary for consumers to discover, learn, and understand your API, add the server or instance information so consumers can invoke the API. Replace `
```suggestion
After the API asset includes all the information necessary for consumers to discover, learn, and understand your API, add the server or instance information so consumers can invoke the API. Replace `:groupId`, `:assetId`, and `:versionGroup` with the group ID, asset ID, and version ID of the API asset:
```

2021-03-18 20:07 UTC, dhirsch1 approved these changes

2021-03-18 20:11 UTC, merged