[EXC-8484] Add new cookie "exchange.loginCSRFToken" in "Cookies used by Exchange"
mulesoft/docs-exchange pull request #172
Opened 2021-12-10 14:07 UTC by guillerecalde

[Link to JIRA ticket](https://www.mulesoft.org/jira/browse/EXC-8484)

## Summary
To prevent CSRF attacks in the Exchange login flow, a new cookie `exchange.loginCSRFToken` has been added. 

## Related Pull Requests
- https://github.com/mulesoft/exchange-ui/pull/4088

2021-12-10 19:50 UTC, wwarner-salesforce approved these changes, later dismissed

2021-12-10 19:50 UTC, wwarner-salesforce commented
Thank you @guillerecalde ! @mcampo would you please check and approve this 1-line change before I merge?

2021-12-13 19:28 UTC, mcampo requested changes

2021-12-13 19:28 UTC, mcampo commented on modules/ROOT/pages/cookies.adoc
> +|exchange.loginCSRFToken |Session |Required |Helps prevent login Cross-Site Request Forgery attacks for site security.
```suggestion
|exchange.loginCSRFToken |Session |Required |Prevent login Cross-Site Request Forgery attacks.
```

2021-12-13 19:31 UTC, wwarner-salesforce commented on modules/ROOT/pages/cookies.adoc
> +|exchange.loginCSRFToken |Session |Required |Helps prevent login Cross-Site Request Forgery attacks for site security.
Good call! Updated to your version.

2021-12-13 20:07 UTC, mcampo approved these changes
👍

2021-12-13 20:16 UTC, sathya0 approved these changes

2021-12-13 20:17 UTC, merged