W 10891383 exchange apigov for ga bsj
mulesoft/docs-exchange pull request #186
Opened 2022-03-31 15:46 UTC by bjoson-mulesoft

2022-04-11 15:41 UTC, JennyHajee requested changes

2022-04-11 15:41 UTC, JennyHajee commented on modules/ROOT/pages/to-create-an-asset.adoc
> += Creating Assets
Until, I can rearchitect this site, let's keep the heading Create an Asset since it is part of the publising workflow.

2022-04-11 15:41 UTC, JennyHajee commented on modules/ROOT/nav.adoc
> + ** xref:to-create-an-asset.adoc[Create Assets]
Keep Create an Asset for now

2022-04-11 15:41 UTC, JennyHajee commented on modules/ROOT/pages/to-create-an-asset.adoc
> +== Create an Asset
Keep the original title since the instructions are referring to APIs and not all assets like a custom asset. Connector assets are not created using Publish new asset button.

2022-04-11 15:41 UTC, JennyHajee commented on modules/ROOT/pages/to-create-an-asset.adoc
> +To create an asset:
Keep API

2022-04-15 00:07 UTC, bjoson-mulesoft commented
This PR will not be used at GA and it now DRAFT only. Instead, Jenny's PR https://github.com/mulesoft/docs-exchange/pull/190 will be used. I've merged her content into the branch associated with this PR because the API Gov GA doc review site points to that branch.

2022-04-28 16:18 UTC, closed without merging