DOCS-3807 Rewrite Change API Version doc
mulesoft/docs-exchange pull request #34
Opened 2019-01-12 03:04 UTC by george-hoffer

2019-01-16 18:23 UTC, LucasLudueno requested changes
Few minor comments to discuss. The rest is amazing!

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
Change the Main file description to: 
`Main file | Specify the main file if the uploaded file is a zip. Otherwise, Exchange uses the same file name as the file you upload.`

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
In the Version description, we should add that if we choose the `minor` or the `patch` version updates we should not change the API version

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +normally not require new versions for minor changes and is a recommended practice
not require a `minor` change but it should require a `patch` change

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +| Add new API operation
what do you mean with `Requires a New Version`? That it requires to increase the `mayor` version?
I ask that because `Add new API operation` should be a `patch` version increase in most of the cases.
The same with the other Not Required changes

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +* Minor versions: When introducing a change to the API that does not require an API user to change, or when fixing a bug.
That description matches with the `Patch versions` change description. A `minor` version increase should be when the user can still using the same API version but the version breaks compatibility with the previous one. There is the description of them https://semver.org/

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +Each API asset contains a field for the *Version*, which is the version number of the asset, and the *API version*, which identifies the version of the API specification. For RAML, OAS,
I would explain somewhere that the Version follows the `semver` convention

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +and SOAP assets, the API specification version is coded inside the specification itself. Because an HTTP API asset is only an endpoint to which you can provide policies or proxies, the API version fi
With the HTTP API the case is the following: because the asset is only an endpoint it makes no sense to increase the `patch` or `minor` of the version in every new publication. So, we only have `major` increases (and because of that it implies that we should change the API version too). I don't know if we should include a similar description of that, what do you think?

2019-01-16 18:23 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +If the Group ID and Asset ID match an existing asset of the same type, a new Asset Version is created. The API Version can be different than the existing one.
sorry, I am not sure if I understood that phrase 🤔 `If the Group ID and Asset ID match an existing asset of the same type, a new Asset Version is created`

2019-01-17 02:38 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
> +| Add new API operation
This came from Damian's spec. I changed "Requires a New Version" to "Changes Requiring a Major Version"

2019-01-17 12:03 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +normally do not require a minor chagne, but should require a patch change.
`chagne` typo

2019-01-17 12:05 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +* Minor versions: When introducing a change to the API that does not require an API user to change, or when fixing a bug. A minor version increase should be when the user can still use the same API v
I would add the Patch versions description, what do you think?

2019-01-17 18:25 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
> +and SOAP assets, the API specification version is coded inside the specification itself. Because an HTTP API asset is only an endpoint to which you can provide policies or proxies, the API version fi
Added as:
For an HTTP API, because the asset is only an endpoint, it makes no sense to increase the patch or minor versions in every new publication. HTTP APIs therefore only have major version increases and also changes to the API version.

2019-01-17 18:26 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
Added as:
|Main file |Specify the main file if the uploaded file is a zip. Otherwise, Exchange uses the same file name as the file you upload.
|Version |The new version number. The Version and API version values need to agree 
in that you can only choose minor version updates for a given API version. To set a major
Version number, also increase the API version. If you choose minor or patch version 
updates, you should not change the API version.

2019-01-17 18:27 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
> +normally do not require a minor chagne, but should require a patch change.
Fixed

2019-01-17 18:30 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
> +* Minor versions: When introducing a change to the API that does not require an API user to change, or when fixing a bug. A minor version increase should be when the user can still use the same API v
Agree: Added as:
* Patch versions: When introducing a backward-compatible change.

2019-01-17 18:30 UTC, george-hoffer commented on modules/ROOT/pages/to-change-raml-version.adoc
> +| Add new API operation
Is this fix ok?

2019-01-17 18:35 UTC, LucasLudueno commented on modules/ROOT/pages/to-change-raml-version.adoc
> +| Add new API operation
for me is ok

2019-01-17 18:35 UTC, LucasLudueno approved these changes

2019-01-19 00:02 UTC, merged